FROM python:3.10-slim

#install system dependencises
RUN apt-get update && \
    apt-get install -y --no-install-recommends \ 
    build-essential \
    wget \
    unzip \
    ca-certificates \
    coinor-cbc \
    glpk-utils \
    libglpk40 \    
    libedit2 \               
    libtinfo6 \
    libc6 \
    libstdc++6 \
    libgl1 \
    libegl1 \
    libosmesa6 \
    libfontconfig1 \
    libfreetype6 \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    libxrandr2 \
    libxi6 \
    libxfixes3 \
    libgpg-error0 \
    && rm -rf /var/lib/apt/lists/*

# Install MiniZinc
RUN wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.9.4/MiniZincIDE-2.9.4-bundle-linux-x86_64.tgz \
    && tar -xzf MiniZincIDE-2.9.4-bundle-linux-x86_64.tgz \
    && mv MiniZincIDE-2.9.4-bundle-linux-x86_64 /opt/minizinc \
    && rm MiniZincIDE-2.9.4-bundle-linux-x86_64.tgz

# Set MiniZinc path
ENV PATH="/opt/minizinc/bin:$PATH"

RUN pip install minizinc

# setup working directory
WORKDIR /sports_tournament_scheduling

# copy source code
COPY source ./source
COPY res ./res
COPY solution_checker.py ./solution_checker.py
COPY entry_point.sh ./entry_point.sh

# ensure res subdirectories exist and are writable
# RUN mkdir -p res/CP res/MIP res/SMT && chmod -R 777 res

# make entrypoint executable
RUN chmod +x entry_point.sh

ENTRYPOINT ["./entry_point.sh"]

CMD []
